### ISSUE TITLE
_parse_binary(): can not work

### ISSUE THREAD

**Issue by fuxiangqiong** [Legisign/Praat-textgrids#1]
>>> import sys
>>> import textgrids
>>> grid = textgrids.TextGrid("/mnt/d/dlib/1424.TextGrid",True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./python3.6/site-packages/textgrids/__init__.py", line 128, in __init__
    self.read(self.filename, binary)
  File "./python3.6/site-packages/textgrids/__init__.py", line 336, in read
    self.parse(infile, binary=True)
  File "./python3.6/site-packages/textgrids/__init__.py", line 166, in parse
    self._parse_binary(data)
  File "./python3.6/site-packages/textgrids/__init__.py", line 302, in _parse_binary
    raise ParseError
textgrids.ParseError: <exception str() failed>
[1424.zip](https://github.com/Legisign/Praat-textgrids/files/3441961/1424.zip)

**Comment by Legisign** [comment]
Sorry, been away for most of this autumn… Looks like you are having a **different** issue than I am with my version 1.3.0.dev6 (where I mainly tried to fixed binary file _writing_).

As for me, the code raises a `BinaryError` while trying to figure out what kind of a tier it’s reading, a point or an interval tier. This most probably means it’s trying to find the descriptive string (either `"PointTier"` or `"IntervalTier"`) somewhere it’s not, i.e., it really shouldn’t be expecting that but something else. As I’ve reverse-engineered the binary textgrid format—didn’t read the Praat source—and I don’t use binary textgrids myself, this will take some figuring :)

**Comment by Legisign** [comment]
Finally had time and motivation to look at this… Looks like the fix is easy but I still cannot understand it. The TextGrid you supplied contains a tier that claims to be a _TextTier_. It works like a PointTier even if it has a different name, and one which I cannot just now find anywhere in Praat’s UI. If I allow TextTiers to be PointTiers just with a different name, everything can be made to work.

**Comment by Legisign** [comment]
I really cannot find a way either to _create_ a TextTier or _convert_ an existing (Point)Tier into a TextTier in Praat. Thus I would say this might be a WONTFIX kind of situation: as far as I can understand, my module handles all the tiers the user is _supposed to_ be creating.
